name: Deploy main & dev

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Pages directories
        run: |
          mkdir -p pages/src
          mkdir -p pages/dev/src

          git fetch origin main --depth=1
          git checkout origin/main -- src
          cp -r src/* pages/src

          git fetch origin dev --depth=1
          git checkout origin/dev -- src
          cp -r src/* pages/dev/src

      - name: Clean Pages folders
        run: |
          find pages -name ".DS_Store" -type f -delete
          find pages -name "._*" -type f -delete
          find pages -type l -exec rm -rf {} +

      - name: Inject secrets into JS
        run: |
          find pages -type f -name "*.js" -exec sed -i 's|__WILD_APRICOT_API_KEY__|${{ secrets.WILD_APRICOT_API_KEY }}|g' {} +
          find pages -type f -name "*.js" -exec sed -i 's|__WILD_APRICOT_ACCOUNT_ID__|${{ secrets.WILD_APRICOT_ACCOUNT_ID }}|g' {} +
          find pages -type f -name "*.js" -exec sed -i 's|__WILD_APRICOT_DEV_ID__|${{ secrets.WILD_APRICOT_DEV_ID }}|g' {} +

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4